ALTER TABLE sea_account ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE knowledge_source ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE knowledge_derivation ADD COLUMN persistence_version BIGINT NOT NULL DEFAULT 0;
